[General]
; Имя файла со списком пользователей (один логин на строку)
UsersFile=users.txt
; Выбор метода: 2 (через AccountManagement) или 3 (через битовые маски LDAP)
Method=3

[SMTP]
; IP-адрес или имя вашего SMTP-сервера. Если оставить пустым, программа выведет результат только в консоль.
Server=192.168.1.50
Port=25
From=ad-alert@yourdomain.com
To=admin@yourdomain.com
Subject=Проверка статуса учетных записей AD